# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - file_regex: ^(application-.*\.yml)$
    encrypted_regex: ^(.*Password|password)$
    key_groups:
      - pgp:
          # Roman
          - 4DEF22A7A7AFFA12
