# .github/workflows/scheduled-tests.yml
name: Scheduled E2E Test Run

on:
  workflow_dispatch:
    inputs:

      environment:
        description: 'Select the environment for test execution'
        required: true
        type: choice
        options:
          - dev
        default: 'dev'

  schedule:
    - cron: '0 1 * * *' # 01:00 UTC (04:00 EEST)

jobs:
  run-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install GnuPG
        run: sudo apt-get update && sudo apt-get install -y gnupg

      - name: Install SOPS
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops_3.8.1_amd64.deb 
          sudo dpkg -i sops_3.8.1_amd64.deb
          rm sops_3.8.1_amd64.deb
      
      - name: Make decrypt script executable
        run: chmod +x ./sops.sh

      - name: Decrypt application*.yml
        env:
          SOPS_PGP_KEY: ${{ secrets.SOPS_PGP_KEY }}
        run: ./sops.sh d

      - name: Verify suite/All.xml exists (DEBUG)
        run: |
          echo "Listing content of current directory:"
          ls -la .
          echo "Listing content of 'suite' directory:"
          ls -la suite/
          echo "Checking if suite/All.xml exists:"
          test -f suite/All.xml && echo "suite/All.xml found!" || echo "ERROR: suite/All.xml NOT found!"
          pwd

      - name: Get Maven Cache Directory
        id: maven-cache-dir
        run: echo "::set-output name=dir::$(mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)"

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.maven-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Maven Tests
        run: |
          SELECTED_PROFILE="${{ github.event.inputs.environment || '' }}"
          MAVEN_PROFILE_ARG=""
          if [ -n "$SELECTED_PROFILE" ]; then
            MAVEN_PROFILE_ARG="-Dspring.profiles.active=$SELECTED_PROFILE"
          fi
          
          mvn clean test $MAVEN_PROFILE_ARG -Dallure.results.directory=${{ github.workspace }}/target/allure-results

      - name: Upload Allure Results (Raw Data)
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Build Allure Report
        if: always() 
        run: |
          mvn allure:report -Dallure.report.url=/SwagLabsTest/
          
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/test-report
